# Can we throw exception from destructor?
